#
PROGRAM = chcsv
OBJS = chcsv.o sqlda.o Option.o OutPut.o Signal.o
CC = gcc

# 
.SUFFIXES: .pc .c .o

# Target
$(PROGRAM): $(OBJS)
	$(CC) -o -L ${ORACLE_HOME}/lib -lclntsh

#
.pc
	gcc -o demoproc demoproc.o -L ${ORACLE_HOME}/lib -lclntsh
#
chcsv.o:	chcsv.c sqlda.c Option.c OutPut.c Signal.c
	gcc  -c demoproc.c -I ${ORACLE_HOME}/precomp/public
#
chcsv.c:	chcsv.pc sqlda.pc Option.pc OutPut.pc Signal.pc
	proc iname=demoproc
#
#
